# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket  = "terraform-state-issy-442042543378"
        key     = "products/project_demo/us-east-1/my/infrastructure/1-ecs/terraform.tfstate"
        region  = "us-east-1"
        dynamodb_table = "terraform-lock-table-issy"
    }
}
